import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "primereact/resources/themes/soho-light/theme.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

import { PrimeReactProvider, PrimeReactContext } from "primereact/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <PrimeReactProvider>
          <div className="flex min-h-screen w-full flex-col">
            {/* <Header /> */}
            {children}
            <Toaster />
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
